### ISSUE TITLE
[Timing bug] Timing goes wrong over time

### ISSUE THREAD

**Issue by dalisoft** [dalisoft/SuperAnimation.js#1]
Hi users.
Today i'm want to explain some issue.
https://dalisoft.github.io/SuperAnimation.js/demos/timeline1.html
See, wait for 1minutes and you see some letter is more differs from previus letter animation delay.
Also, try change tab and again see for faster result (not 1min, quicker).

See image of issue: https://i.stack.imgur.com/dHK1e.png

We can fix this?

**Comment by dalisoft** [comment]
Fixed in <a href="https://github.com/dalisoft/SuperAnimation.js/commit/104cd505ee5a80136b774e5b164d320187d33f0a">this commit</a>

**Comment by dalisoft** [comment]
It happens too sometimes

**Comment by thednp** [comment]
I think this relates to this change:
https://github.com/tweenjs/tween.js/commit/37dccbe7e669b5375268edff067ab4c541207ae8

But I'm not sure.

**Comment by dalisoft** [comment]
No. Its another issue

**Comment by dalisoft** [comment]
Thanks for reply

**Comment by dalisoft** [comment]
Wow, i realised what caused this bug. I as soon make new release with fixed issue. Now it's bug-free will be until someone finds issue
